server:
  port: 7777

spring:
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/Contabilidad
    username: root
    password: 1234post
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

springdoc:
  pathsToMatch: /**
  packagesToScan: com.microservicios.Pedidos.Controller

